etfs:
  XLV: Health Care
  XLI: Industrials
  XLK: Technology
  XLRE: Real Estate
  XLE: Energy
  XLP: Consumer Staples
  XLY: Consumer Discretionary
  XLF: Financials
  XLC: Communication Services
  XLU: Utilities
  XLB: Materials
  XBI: Biotechnology
periods:
  - 1d
  - 5d
  - 1mo
  - 3mo
  - 6mo
  - 1y
period_weights:
  short_term:
    1d: 0.2
    5d: 0.4
    1mo: 0.4
  long_term:
    3mo: 0.5
    6mo: 0.3
    1y: 0.2
thresholds:
  momentum: 0.2
  bias: 0.5
  neutral: 0.1
short_term_periods:
  - 1d
  - 5d
  - 1mo
long_term_periods:
  - 3mo
  - 6mo
  - 1y